### ISSUE TITLE
Cassandra: Ability to install from a remote tarball

### ISSUE THREAD

**Issue by tjake** [riptano/jepsen#1]

**Comment by jkni** [comment]
Starting work on this

**Comment by tjake** [comment]
Noticed you have a checked in resource/cassandra.yaml etc.  Why not use the included one with the tarball and run sed// on it?

**Comment by tjake** [comment]
Also as we spoke about, Please change to check the env for a CASSANDRA_TARBALL_URL variable and use that vs the default

**Comment by jkni** [comment]
Both fixed in https://github.com/riptano/jepsen/commit/6cbdd079252121c76d152ef6834f1f3bba971954
