### ISSUE TITLE
Validate durability of commit log

### ISSUE THREAD

**Issue by tjake** [riptano/jepsen#10]
We should have a kill-9 operation. and verify we don't lose data.

This will require changing the default commitlog settings in the yaml

http://docs.datastax.com/en/cassandra/2.0/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__commitlog_sync

**Comment by jkni** [comment]
Kill -9 nemeses are being used/will be used with the batch commitlog_sync setting for all models.
